# numpy boolean arrays
- can be made by 'vector compares'
- can be used as indexes
- super useful

In [1]:
import numpy as np

def sqmat(n):
    # make 1D array
    a=np.array(range(n*n))
    # reshape to 2D
    s = a.reshape(n,n)
    return(s)


a = sqmat(3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [2]:
# make a boolean array
# 'vector op scalar' (the 4 is broadcasted)

b = a > 4
b

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [3]:
# when a boolean array is used as an index,
# the array elements at the same position 
# as True elements are placed in a 1D array!!
# so get elements of b greater than 4

a[b]

array([5, 6, 7, 8])

In [4]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# negate some elements
# note '&' instead of 'and'

a[(3 < a) & (a <= 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [6]:
# 'all' ANDs together all the array elements
# there are False elements, so 'AND' must 
# be False. does "short circuit" evaluation

b.all()

False

In [7]:
# 'any' ORs together all the array elements
# there are True elements, so 'OR' must 
# be True. does "short circuit" evaluation

b.any()

True

In [8]:
o = np.ones((3,3))
o

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
r = np.random.randint(0,3,(3,3))
r

array([[0, 1, 2],
       [0, 1, 1],
       [2, 1, 0]])

In [10]:
# vector compare - 'vector op vector'
# result of comparison is a boolean array of same shape

ba = o == r
ba

array([[False,  True, False],
       [False,  True,  True],
       [False,  True, False]])

In [11]:
# count the Trues (True is 1, False is 0)

np.count_nonzero(ba), ba.sum(), np.sum(ba)

(4, 4, 4)

In [ ]:
# make a boolean array from a boolean array
# invert truth vals

ba2 = ba == False
ba2

In [ ]:
r

In [ ]:
# select elements != 1

r[ba2]